version: "2.4"

services:
  mock:
    image: vedrouniverse/jj
    ports:
      - "8080:80"

  proxy:
    image: fsouza/docker-ssl-proxy:1.5
    environment:
      TARGET_HOST: mock
      TARGET_PORT: 80
    ports:
      - "4443:443"
